import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import type { ImportTemplateKey } from "@shared/importTemplates";
import { validateCsvImport, type CsvImportPreview } from "@shared/csvImportValidation";
import { AlertTriangle, CheckCircle2, Download, Eye, FileSpreadsheet, ShieldCheck, Upload } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const templates: { key: ImportTemplateKey; label: string; note: string }[] = [
  { key: "groups", label: "小組資料", note: "先建立小組與指派帶領人。" },
  { key: "group_members", label: "小組成員", note: "建議填寫 email 或電話，方便後續主檔連結。" },
  { key: "meetings", label: "小組聚會", note: "聚會時間使用 ISO 8601 格式。" },
  { key: "attendance", label: "出席紀錄", note: "先導入小組、成員與聚會。" },
  { key: "care_logs", label: "關懷日誌", note: "避免將高度敏感敘述留在未受控設備。" },
  { key: "pastoral_tasks", label: "牧養待辦", note: "可用於待辦分類與 Leader 範圍的最終驗收。" },
];

export default function DataImportTemplates() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const [preview, setPreview] = useState<CsvImportPreview | null>(null); const [previewLabel, setPreviewLabel] = useState(""); const [previewFileName, setPreviewFileName] = useState("");
  const download = trpc.governance.downloadImportTemplate.useMutation({ onSuccess: data => { const url = URL.createObjectURL(new Blob([data.csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = data.filename; link.click(); URL.revokeObjectURL(url); utils.governance.auditLogs.invalidate(); toast.success(`已下載「${data.label}」模板`); }, onError: error => toast.error(error.message) });
  const previewFile = (template: ImportTemplateKey, label: string, file?: File) => { if (!file) return; if (file.size > 2_000_000) { setPreview({ headers: [], rows: [], errors: ["檔案超過 2MB，本機預覽已停止。"], warnings: [] }); setPreviewLabel(label); setPreviewFileName(file.name); return; } const reader = new FileReader(); reader.onload = () => { setPreview(validateCsvImport(template, String(reader.result ?? ""))); setPreviewLabel(label); setPreviewFileName(file.name); }; reader.onerror = () => toast.error("無法在瀏覽器中讀取此檔案。"); reader.readAsText(file, "utf-8"); };
  if (user?.role !== "Admin") return <Card className="border-[#e3dbcf] bg-[#fdfcf9]"><CardContent className="py-16 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-[#b07b51]" /><h2 className="mt-4 font-serif text-2xl text-[#405a49]">資料導入模板僅限 Admin</h2><p className="mt-2 text-sm text-[#78827b]">模板用於準備真實教會資料，不包含會友或牧養示例資料。</p></CardContent></Card>;
  return <div className="space-y-6"><Card className="border-[#d7e4d5] bg-[#f8fbf7] shadow-none"><CardHeader><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f1e7] text-[#477258]"><FileSpreadsheet className="h-5 w-5" /></div><div><CardTitle className="font-serif text-2xl text-[#405a49]">真實資料導入模板</CardTitle><CardDescription className="mt-1">每份下載檔僅包含欄位標頭，不包含任何虛構會友、關懷或牧養資料。</CardDescription></div></div></CardHeader><CardContent><p className="text-sm leading-6 text-[#66766a]">請先離線整理並由資料管理者覆核真實資料。下方「本機預覽」只在目前瀏覽器解析 CSV，檔案內容不會傳送或儲存至伺服器。</p></CardContent></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{templates.map(template => <Card key={template.key} className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader className="pb-3"><CardTitle className="font-serif text-xl text-[#405a49]">{template.label}</CardTitle><CardDescription>{template.note}</CardDescription></CardHeader><CardContent className="space-y-2"><Button variant="outline" disabled={download.isPending} onClick={() => download.mutate({ template: template.key })} className="w-full rounded-xl border-[#d7d0c4] text-[#52665b]"><Download className="mr-2 h-4 w-4 text-[#a06c3b]" />下載 CSV 模板</Button><label className="flex cursor-pointer items-center justify-center rounded-xl border border-dashed border-[#d9d1c6] px-3 py-2 text-sm text-[#68756b] hover:bg-[#faf8f4]"><Upload className="mr-2 h-4 w-4 text-[#758f7a]" />本機預覽 CSV<Input type="file" accept=".csv,text/csv" className="hidden" onChange={event => previewFile(template.key, template.label, event.target.files?.[0])} /></label></CardContent></Card>)}</div>{preview && <PreviewCard label={previewLabel} fileName={previewFileName} preview={preview} />}<Card className="border-[#ead8c2] bg-[#fffaf3] shadow-none"><CardContent className="flex gap-3 p-5"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-[#a8743c]" /><div><p className="font-medium text-[#765330]">安全導入提醒</p><p className="mt-1 text-sm leading-6 text-[#8a6a46]">請僅在受管理、受加密的設備整理檔案；不要以未加密通訊軟體傳送關懷摘要、聯絡資訊或待辦細節。正式匯入功能上線前，請先由 Admin 依「上線驗收」頁完成資料條件檢核。</p></div></CardContent></Card></div>;
}

function PreviewCard({ label, fileName, preview }: { label: string; fileName: string; preview: CsvImportPreview }) {
  const passed = preview.errors.length === 0;
  return <Card className={`border shadow-none ${passed ? "border-[#d4e3d2] bg-[#fbfdfb]" : "border-[#efd4ce] bg-[#fffaf9]"}`}><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><CardTitle className="font-serif text-xl text-[#405a49]">本機 CSV 預覽：{label}</CardTitle><CardDescription className="mt-1">{fileName} · 僅在目前瀏覽器記憶體處理。</CardDescription></div><Badge variant="outline" className={passed ? "border-[#d0dfd0] bg-[#eff5ed] text-[#50755a]" : "border-[#ecd0c9] bg-[#fff0ed] text-[#a55446]"}>{passed ? "欄位驗證通過" : `${preview.errors.length} 項問題`}</Badge></div></CardHeader><CardContent className="space-y-4">{preview.warnings.map(warning => <p key={warning} className="rounded-xl bg-[#fff6e7] p-3 text-sm text-[#936a31]">{warning}</p>)}{preview.errors.length > 0 && <div className="rounded-xl bg-[#fff1ee] p-4"><p className="font-medium text-[#93463a]">請先修正以下問題</p><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-[#9c554a]">{preview.errors.map(error => <li key={error}>{error}</li>)}</ul></div>}<div><p className="mb-2 flex items-center gap-2 font-medium text-[#5b6b60]"><Eye className="h-4 w-4 text-[#75917b]" />前五列本機預覽（共 {preview.rows.length} 列）</p>{preview.headers.length ? <div className="overflow-x-auto rounded-xl border border-[#e5dfd5]"><table className="w-full min-w-160 text-left text-xs"><thead className="bg-[#f6f3ed]"><tr>{preview.headers.map(header => <th key={header} className="whitespace-nowrap px-3 py-2 font-semibold text-[#667167]">{header}</th>)}</tr></thead><tbody>{preview.rows.slice(0, 5).map((row, index) => <tr key={index} className="border-t border-[#eee9e1]">{preview.headers.map(header => <td key={header} className="max-w-52 truncate px-3 py-2 text-[#657169]">{row[header] || "—"}</td>)}</tr>)}</tbody></table></div> : <p className="text-sm text-[#8b918b]">尚無可預覽欄位。</p>}</div>{passed && preview.rows.length > 0 && <div className="flex items-center gap-2 rounded-xl bg-[#eff6ed] p-3 text-sm text-[#50775a]"><CheckCircle2 className="h-4 w-4" />此檔案已通過本機欄位格式檢查；正式匯入前仍需由資料管理者覆核內容。</div>}</CardContent></Card>;
}
