import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { CalendarCheck2, Check, CircleAlert, ClipboardCheck, Clock3, UserPlus, UsersRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

const dateTime = (value: Date | string | number) => new Date(value).toLocaleString("zh-TW", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" });

export default function EventRegistrationCenter() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const [eventId, setEventId] = useState<string>(""); const [personId, setPersonId] = useState<string>("");
  const events = trpc.activities.events.useQuery(undefined, { enabled: user?.role === "Admin" }); const people = trpc.people.list.useQuery(undefined, { enabled: user?.role === "Admin" });
  useEffect(() => { if (!eventId && events.data?.length) setEventId(String(events.data[0].id)); }, [eventId, events.data]);
  const selectedEvent = events.data?.find(event => event.id === Number(eventId)); const registrations = trpc.activities.registrations.useQuery({ eventId: Number(eventId) }, { enabled: user?.role === "Admin" && !!eventId });
  const refresh = () => { registrations.refetch(); utils.activities.events.invalidate(); };
  const register = trpc.activities.register.useMutation({ onSuccess: data => { refresh(); toast.success(data.unchanged ? "此人已在名單中" : data.status === "registered" ? "已完成活動報名" : "活動已額滿，已列為候補"); setPersonId(""); }, onError: error => toast.error(error.message) });
  const cancel = trpc.activities.cancelRegistration.useMutation({ onSuccess: () => { refresh(); toast.success("已取消活動報名"); }, onError: error => toast.error(error.message) });
  const checkIn = trpc.activities.checkIn.useMutation({ onSuccess: () => { refresh(); toast.success("已完成簽到"); }, onError: error => toast.error(error.message) });
  const active = useMemo(() => (registrations.data ?? []).filter(item => item.status === "registered"), [registrations.data]); const waitlisted = useMemo(() => (registrations.data ?? []).filter(item => item.status === "waitlisted"), [registrations.data]);
  if (user?.role !== "Admin") return <Card className="border-[#e3dbcf] bg-[#fdfcf9]"><CardContent className="py-16 text-center"><CircleAlert className="mx-auto h-9 w-9 text-[#b07b51]" /><h2 className="mt-4 font-serif text-2xl text-[#405a49]">活動報名管理僅限 Admin</h2><p className="mt-2 text-sm text-[#78827b]">此區包含完整名單、聯絡方式與簽到紀錄。</p></CardContent></Card>;
  return <div className="space-y-6"><Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><CardTitle className="font-serif text-2xl text-[#405a49]">活動報名與簽到</CardTitle><CardDescription className="mt-1">由中央人員主檔建立 RSVP，系統會依容量自動將超額人員列為候補。</CardDescription></CardHeader><CardContent className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="flex-1"><Label>選擇活動</Label><Select value={eventId} onValueChange={setEventId}><SelectTrigger className="mt-2"><SelectValue placeholder="選擇活動" /></SelectTrigger><SelectContent>{events.data?.map(event => <SelectItem key={event.id} value={String(event.id)}>{event.title} · {dateTime(event.startsAt)}</SelectItem>)}</SelectContent></Select></div>{selectedEvent && <div className="rounded-xl bg-[#eef4ec] px-4 py-3 text-sm text-[#52705b]">容量：{selectedEvent.capacity ?? "不限"}<span className="ml-3">已報名：{active.length}</span><span className="ml-3">候補：{waitlisted.length}</span></div>}</CardContent></Card>
    {selectedEvent ? <div className="grid gap-6 xl:grid-cols-[0.82fr_1.18fr]"><Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><CardTitle className="font-serif text-xl text-[#405a49]">新增 RSVP</CardTitle><CardDescription>僅列出已啟用的中央人員。</CardDescription></CardHeader><CardContent className="space-y-4"><div><Label>人員</Label><Select value={personId} onValueChange={setPersonId}><SelectTrigger className="mt-2"><SelectValue placeholder="選擇人員" /></SelectTrigger><SelectContent>{people.data?.filter(person => person.status === "active").map(person => <SelectItem key={person.id} value={String(person.id)}>{person.fullName}{person.householdName ? ` · ${person.householdName}` : ""}</SelectItem>)}</SelectContent></Select></div><Button disabled={!personId || register.isPending} onClick={() => register.mutate({ eventId: selectedEvent.id, personId: Number(personId) })} className="w-full rounded-xl bg-[#355f4d] hover:bg-[#294a3d]"><UserPlus className="mr-2 h-4 w-4" />加入活動名單</Button>{!people.data?.length && <p className="rounded-xl bg-[#fbf4ed] p-3 text-xs leading-5 text-[#91643f]">請先在「人員主檔」建立真實參加者資料，再建立 RSVP。</p>}</CardContent></Card><RegistrationList items={registrations.data ?? []} pending={cancel.isPending || checkIn.isPending} onCancel={person => cancel.mutate({ eventId: selectedEvent.id, personId: person })} onCheckIn={person => checkIn.mutate({ eventId: selectedEvent.id, personId: person })} /></div> : <Card className="border-[#e3dbcf] bg-[#fdfcf9]"><CardContent className="py-16 text-center"><CalendarCheck2 className="mx-auto h-9 w-9 text-[#9aab9e]" /><p className="mt-3 font-medium text-[#5d6e62]">尚無可管理活動</p><p className="mt-1 text-sm text-[#8b918b]">請先在活動行事曆建立活動與容量。</p></CardContent></Card>}</div>;
}

function RegistrationList({ items, onCancel, onCheckIn, pending }: { items: { id: number; personId: number; personName: string; personEmail: string | null; personPhone: string | null; status: "registered" | "waitlisted" | "cancelled"; checkedInAt: Date | null }[]; onCancel: (id: number) => void; onCheckIn: (id: number) => void; pending: boolean }) { return <Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><CardTitle className="font-serif text-xl text-[#405a49]">報名名單</CardTitle><CardDescription>候補與取消者不會列入簽到名單。</CardDescription></CardHeader><CardContent>{items.length ? <div className="divide-y divide-[#eee9e1]">{items.map(item => <div key={item.id} className="flex flex-col gap-3 py-3 first:pt-0 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium text-[#52645a]">{item.personName}</p><p className="mt-1 text-xs text-[#8f978f]">{item.personEmail || item.personPhone || "聯絡方式待補"}</p></div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline" className={item.status === "registered" ? "border-[#d0dfd0] bg-[#eff5ed] text-[#50755a]" : item.status === "waitlisted" ? "border-[#ead9b9] bg-[#fcf6e8] text-[#9b6f32]" : "border-[#e3d8cf] bg-[#f5f1ed] text-[#8a7b6d]"}>{item.status === "registered" ? "已報名" : item.status === "waitlisted" ? "候補" : "已取消"}</Badge>{item.checkedInAt ? <Badge variant="outline" className="border-[#d5e2eb] bg-[#eef5f8] text-[#4b7488]">已簽到</Badge> : item.status === "registered" ? <Button size="sm" variant="outline" disabled={pending} onClick={() => onCheckIn(item.personId)} className="rounded-lg"><ClipboardCheck className="mr-1 h-3.5 w-3.5" />簽到</Button> : null}{item.status !== "cancelled" && <Button size="sm" variant="ghost" disabled={pending} onClick={() => onCancel(item.personId)} className="rounded-lg text-[#9b6650]"><X className="mr-1 h-3.5 w-3.5" />取消</Button>}</div></div>)}</div> : <div className="py-12 text-center"><UsersRound className="mx-auto h-8 w-8 text-[#a8b8aa]" /><p className="mt-3 font-medium text-[#5d6e62]">尚無 RSVP</p><p className="mt-1 text-sm text-[#8b918b]">選擇中央人員後，即可建立第一筆活動報名。</p></div>}</CardContent></Card>; }
