import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ContactRound, House, Link2, PencilLine, Plus, Search, Unlink, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type Tab = "people" | "households" | "links";

export default function PeopleDirectory() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const [tab, setTab] = useState<Tab>("people"); const [search, setSearch] = useState(""); const [editingId, setEditingId] = useState<number | null>(null);
  const people = trpc.people.list.useQuery(undefined, { enabled: user?.role === "Admin" });
  const households = trpc.people.households.useQuery(undefined, { enabled: user?.role === "Admin" });
  const groupMembers = trpc.people.groupMembersForLink.useQuery(undefined, { enabled: user?.role === "Admin" });
  const refresh = () => { utils.people.list.invalidate(); utils.people.households.invalidate(); utils.people.groupMembersForLink.invalidate(); };
  const createPerson = trpc.people.create.useMutation({ onSuccess: () => { refresh(); toast.success("人員主檔已建立"); }, onError: error => toast.error(error.message) });
  const updatePerson = trpc.people.update.useMutation({ onSuccess: () => { refresh(); toast.success("人員主檔已更新"); setEditingId(null); }, onError: error => toast.error(error.message) });
  const createHousehold = trpc.people.createHousehold.useMutation({ onSuccess: () => { refresh(); toast.success("家庭主檔已建立"); }, onError: error => toast.error(error.message) });
  const linkMember = trpc.people.linkGroupMember.useMutation({ onSuccess: () => { refresh(); toast.success("小組成員連結已更新"); }, onError: error => toast.error(error.message) });
  const filteredPeople = useMemo(() => (people.data ?? []).filter(person => `${person.fullName} ${person.email ?? ""} ${person.phone ?? ""} ${person.householdName ?? ""}`.toLocaleLowerCase("zh-TW").includes(search.trim().toLocaleLowerCase("zh-TW"))), [people.data, search]);
  const editing = people.data?.find(person => person.id === editingId);
  if (user?.role !== "Admin") return <Card className="border-[#e3dbcf] bg-[#fdfcf9]"><CardContent className="py-16 text-center"><ContactRound className="mx-auto h-9 w-9 text-[#9aab9e]" /><h2 className="mt-4 font-serif text-2xl text-[#405a49]">人員主檔僅限 Admin 使用</h2><p className="mt-2 text-sm text-[#78827b]">此區集中管理行政聯絡資料與家庭關係，以維護資料品質。</p></CardContent></Card>;
  if (people.isError || households.isError || groupMembers.isError) return <Card className="border-[#edcfca] bg-[#fffaf8]"><CardContent className="py-16 text-center"><AlertTriangle className="mx-auto h-9 w-9 text-[#b65b4c]" /><h2 className="mt-4 font-serif text-2xl text-[#7d4037]">人員資料暫時無法載入</h2><Button onClick={() => { people.refetch(); households.refetch(); groupMembers.refetch(); }} className="mt-6 rounded-xl bg-[#8b4f43] hover:bg-[#713d34]">重新整理</Button></CardContent></Card>;
  return <div className="space-y-6"><section className="grid gap-3 sm:grid-cols-3"><Metric icon={ContactRound} label="中央人員" value={people.data?.length ?? 0} /><Metric icon={House} label="家庭主檔" value={households.data?.length ?? 0} /><Metric icon={Link2} label="已連結小組成員" value={(groupMembers.data ?? []).filter(member => member.personId).length} /></section>
    <div className="flex flex-wrap gap-2 rounded-2xl border border-[#e4ddd3] bg-[#fdfcf9] p-2">{(["people", "households", "links"] as Tab[]).map(item => <Button key={item} size="sm" variant={tab === item ? "default" : "ghost"} onClick={() => setTab(item)} className={tab === item ? "rounded-xl bg-[#355f4d] hover:bg-[#294a3d]" : "rounded-xl text-[#68766c]"}>{({ people: "人員名冊", households: "家庭主檔", links: "小組成員連結" } as Record<Tab, string>)[item]}</Button>)}</div>
    {tab === "people" && <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle className="font-serif text-xl text-[#405a49]">中央人員名冊</CardTitle><CardDescription className="mt-1">將人員資料集中維護；系統會阻擋可能重複的姓名、信箱或電話。</CardDescription></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#98a197]" /><Input value={search} onChange={event => setSearch(event.target.value)} className="w-full pl-9 sm:w-60" placeholder="搜尋姓名、信箱、電話" /></div></div></CardHeader><CardContent>{people.isLoading ? <p className="py-12 text-center text-sm text-[#859087]">正在整理人員資料…</p> : filteredPeople.length ? <div className="space-y-2">{filteredPeople.map(person => <button type="button" key={person.id} onClick={() => setEditingId(person.id)} className={`flex w-full items-center justify-between rounded-xl border p-4 text-left transition ${editingId === person.id ? "border-[#8bad92] bg-[#f1f7f0]" : "border-[#ebe4d9] bg-[#fcfaf6] hover:border-[#cad8c9]"}`}><span><span className="font-medium text-[#465b4d]">{person.fullName}</span><span className="mt-1 block text-xs text-[#858d85]">{person.email || person.phone || "尚未填寫聯絡方式"}{person.householdName ? ` · ${person.householdName}` : ""}</span></span><Badge variant="outline" className={person.status === "active" ? "border-[#d0dfd0] bg-[#eff5ed] text-[#50755a]" : "border-[#e6d7ca] bg-[#fbf4ed] text-[#94613d]"}>{person.status === "active" ? "啟用" : "停用"}</Badge></button>)}</div> : <Empty icon={UsersRound} title="尚無符合條件的人員" text="請建立第一筆中央人員主檔，或調整搜尋關鍵字。" />}</CardContent></Card><PersonForm key={editing?.id ?? "new"} person={editing} households={households.data ?? []} pending={createPerson.isPending || updatePerson.isPending} onCancel={() => setEditingId(null)} onSave={data => editing ? updatePerson.mutate({ id: editing.id, ...data }) : createPerson.mutate(data)} /></div>}
    {tab === "households" && <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><CardTitle className="font-serif text-xl text-[#405a49]">建立家庭主檔</CardTitle><CardDescription className="mt-1">只保存行政必要聯絡資料；不在此區儲存高敏感個資。</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); createHousehold.mutate({ name: String(data.get("name")).trim(), primaryPhone: String(data.get("phone") || "") || null, notes: String(data.get("notes") || "") || null, status: "active" }); event.currentTarget.reset(); }}><div><Label>家庭名稱</Label><Input name="name" required className="mt-2" placeholder="例如：王家" /></div><div><Label>主要聯絡電話</Label><Input name="phone" className="mt-2" placeholder="選填" /></div><div><Label>行政備註</Label><Textarea name="notes" className="mt-2" placeholder="選填；勿放入關懷內容或高敏感資訊" /></div><Button type="submit" disabled={createHousehold.isPending} className="w-full rounded-xl bg-[#355f4d] hover:bg-[#294a3d]"><Plus className="mr-2 h-4 w-4" />建立家庭</Button></form></CardContent></Card><Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><CardTitle className="font-serif text-xl text-[#405a49]">現有家庭主檔</CardTitle><CardDescription className="mt-1">家庭名稱可在建立或編輯人員時關聯。</CardDescription></CardHeader><CardContent>{households.data?.length ? <div className="grid gap-2 sm:grid-cols-2">{households.data.map(household => <div key={household.id} className="rounded-xl border border-[#ebe4d9] bg-[#fcfaf6] p-4"><p className="font-medium text-[#465b4d]">{household.name}</p><p className="mt-1 text-xs text-[#858d85]">{household.primaryPhone || "未填主要電話"}</p></div>)}</div> : <Empty icon={House} title="尚無家庭主檔" text="建立家庭後，可將人員分組至同一家庭。" />}</CardContent></Card></div>}
    {tab === "links" && <Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><CardTitle className="font-serif text-xl text-[#405a49]">小組成員連結</CardTitle><CardDescription className="mt-1">將既有小組成員選擇性連結至中央人員。未連結的既有名冊不會受到影響。</CardDescription></CardHeader><CardContent>{groupMembers.data?.length ? <div className="space-y-3">{groupMembers.data.map(member => <div key={member.id} className="flex flex-col gap-3 rounded-xl border border-[#ebe4d9] bg-[#fcfaf6] p-4 md:flex-row md:items-center md:justify-between"><div><p className="font-medium text-[#465b4d]">{member.name}<span className="ml-2 text-sm font-normal text-[#859087]">{member.groupName}</span></p><p className="mt-1 text-xs text-[#858d85]">{member.email || member.phone || "無聯絡資料"}{member.personId ? " · 已連結" : " · 尚未連結"}</p></div><div className="flex items-center gap-2"><Select value={member.personId ? String(member.personId) : "unlinked"} onValueChange={value => linkMember.mutate({ groupMemberId: member.id, personId: value === "unlinked" ? null : Number(value) })}><SelectTrigger className="w-52"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="unlinked">不連結中央人員</SelectItem>{people.data?.map(person => <SelectItem key={person.id} value={String(person.id)}>{person.fullName}{person.householdName ? ` · ${person.householdName}` : ""}</SelectItem>)}</SelectContent></Select>{member.personId ? <Unlink className="h-4 w-4 text-[#aa7864]" /> : <Link2 className="h-4 w-4 text-[#6d8a72]" />}</div></div>)}</div> : <Empty icon={Link2} title="尚無小組成員" text="建立小組與成員後，便可在此連結至中央人員。" />}</CardContent></Card>}</div>;
}

function PersonForm({ person, households, onSave, onCancel, pending }: { person?: { id: number; fullName: string; email: string | null; phone: string | null; householdId: number | null; status: "active" | "inactive" }; households: { id: number; name: string }[]; onSave: (data: { fullName: string; email: string | null; phone: string | null; householdId: number | null; status: "active" | "inactive"; allowPossibleDuplicate: boolean }) => void; onCancel: () => void; pending: boolean }) {
  const [status, setStatus] = useState<"active" | "inactive">(person?.status ?? "active"); const [householdId, setHouseholdId] = useState(person?.householdId ? String(person.householdId) : "none");
  return <Card className="border-[#e3dbcf] bg-[#fdfcf9] shadow-none"><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="font-serif text-xl text-[#405a49]">{person ? "編輯人員主檔" : "建立人員主檔"}</CardTitle><CardDescription className="mt-1">若資料疑似重複，系統會要求您先確認。</CardDescription></div>{person && <Button variant="ghost" size="sm" onClick={onCancel} className="text-[#7d7268]">取消編輯</Button>}</div></CardHeader><CardContent><form className="space-y-4" onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); onSave({ fullName: String(data.get("fullName")).trim(), email: String(data.get("email") || "") || null, phone: String(data.get("phone") || "") || null, householdId: householdId === "none" ? null : Number(householdId), status, allowPossibleDuplicate: false }); }}><div><Label>姓名</Label><Input name="fullName" required defaultValue={person?.fullName ?? ""} className="mt-2" /></div><div><Label>電子郵件</Label><Input name="email" type="email" defaultValue={person?.email ?? ""} className="mt-2" placeholder="選填" /></div><div><Label>電話</Label><Input name="phone" defaultValue={person?.phone ?? ""} className="mt-2" placeholder="選填" /></div><div><Label>所屬家庭</Label><Select value={householdId} onValueChange={setHouseholdId}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">不指定家庭</SelectItem>{households.map(household => <SelectItem key={household.id} value={String(household.id)}>{household.name}</SelectItem>)}</SelectContent></Select></div><div><Label>狀態</Label><Select value={status} onValueChange={value => setStatus(value as "active" | "inactive")}><SelectTrigger className="mt-2"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">啟用</SelectItem><SelectItem value="inactive">停用</SelectItem></SelectContent></Select></div><Button type="submit" disabled={pending} className="w-full rounded-xl bg-[#355f4d] hover:bg-[#294a3d]"><PencilLine className="mr-2 h-4 w-4" />{person ? "儲存變更" : "建立人員"}</Button></form></CardContent></Card>;
}

function Metric({ icon: Icon, label, value }: { icon: typeof ContactRound; label: string; value: number }) { return <Card className="border-[#e7dfd5] bg-[#fdfcf9] shadow-none"><CardContent className="flex items-center gap-4 p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf5ee] text-[#477258]"><Icon className="h-5 w-5" /></div><div><p className="text-sm text-[#7e887f]">{label}</p><p className="mt-0.5 font-serif text-3xl text-[#405a49]">{value}</p></div></CardContent></Card>; }
function Empty({ icon: Icon, title, text }: { icon: typeof ContactRound; title: string; text: string }) { return <div className="py-12 text-center"><Icon className="mx-auto h-8 w-8 text-[#a8b8aa]" /><p className="mt-3 font-medium text-[#5d6e62]">{title}</p><p className="mt-1 text-sm text-[#8b918b]">{text}</p></div>; }
